### ISSUE TITLE
Used - https://multichain.xyz/ (FTM) not received 

### ISSUE THREAD

**Issue by DGGOKU** [anyswap/Anyswap-Audit#13]
Just yesterday used https://multichain.xyz/ to bridge Ethereum network FTM over to Fantom opera network connected metamask and while bridging FTM, it buffered for a long time with not confirmation of swap being successful on the website. Can see the transaction has been successful and tokens transferred from my address to an address of https://multichain.xyz/ 0x5cBE98480A790554403694b98BFf71A525907f5d still yet to receive my FTM into my Fantom opera wallet? 

![IMG_1231](https://user-images.githubusercontent.com/95108115/143661501-468d64b3-cfb2-4df1-90a5-0dd3b951bbe4.jpg)

**Comment by solglide** [comment]
yes, it has been 20 hrs since my FTM was transferred to them... no sign of receiving them back to my wallet yet... hopefully soon...

**Comment by DGGOKU** [comment]
Noticed i received my FTM the following day of posting this. Hope you have as well.

**Comment by c1cio** [comment]
I cant access links that are inside of emails sent to me so I have no way
of accessing the information that a link would point to.. this
commynication has 13 as the resolution but I cant see what 13 is because
someone has control over my devices and has installed software scripts that
I have no control of nor did I collaborate or authorize an entity to
install software on my devices that restrict communications of information.
Please send communications without hyperlinks so that I can be aware of how
to locate the information if it is not contained in the communication
itself for security reasons. c1c
